# Testing for Late Fusion Techniques

### Here we aim to combine the discriminative powers of:

1. Structural Features (FUSE embeddings)
2. Semantic Features (Word-2-Vec) [provided in the OGBN benchmark dataset]

### Two techniques were tested:

1. Simple Concatenation
2. Contrastive Alignment (CLIP-based)

## Results Summary


| Split Type | Fusion Technique | Classifier | Test Accuracy | Weighted Avg F1 Score |
|---|---|---|---:|---:|
| OGBN Official Split | Simple Concatenation | MLP | **0.7029** | **0.6870** |
| OGBN Official Split | Simple Concatenation | Multinomial Logistic Regression | **0.4760** | **0.4281** |
| OGBN Official Split | CLIP-based Contrastive Alignment | MLP | **0.6941** | **0.6792** |
| OGBN Official Split | CLIP-based Contrastive Alignment | Multinomial Logistic Regression | **0.7633** | **0.7558** |
| 30-70 Split | Simple Concatenation | MLP | **0.8498** | **0.8409** |
| 30-70 Split | Simple Concatenation | Multinomial Logistic Regression | **0.7910** | **0.7772** |
| 30-70 Split | CLIP-based Contrastive Alignment | MLP | **0.8722** | **0.8654** |
| 30-70 Split | CLIP-based Contrastive Alignment | Multinomial Logistic Regression | **0.8552** | **0.8489** |


## Interpretation


- Simple concatenation directly combines the two feature types without explicitly aligning their embedding geometries. Therefore, it may require a more expressive nonlinear classifier such as an MLP to extract useful interactions between structural and semantic information.

- In contrast, CLIP-based contrastive alignment aims to learn a shared representation space where the two feature types are geometrically aligned. If this learned representation is effective, it should become more linearly separable.

Thus, better performance with multinomial logistic regression indicates that the CLIP-based fusion method produces a cleaner and more discriminative embedding.

In [1]:
!pip install ogb
!pip install torch_geometric

import torch
import numpy as np
from torch_geometric.datasets import Planetoid
from torch_geometric.utils import to_torch_csr_tensor   

import torch
from ogb.nodeproppred import NodePropPredDataset 


import wandb 
from sklearn.linear_model import LogisticRegression

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

Collecting ogb
  Downloading ogb-1.3.6-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.4.6)
Requirement already satisfied: tqdm>=4.29.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (4.67.3)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (1.6.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.3.3)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (1.17.0)
Requirement already satisfied: urllib3>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.5.0)
Collecting outdated>=0.2.0 (from ogb)
  Downloading outdated-0.2.2-py2.py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: setuptools>=44 in /usr/local/lib/python3.12/dist-packages (from outdated>=0.2.0->ogb) (75.2.0)
Collecting littleutils (from outdated>=0.2.0->ogb)
  Downloading littleutils-0.2.4-py3-none-any.whl.metadata (679 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from outdated>=0.2.0->ogb) (2.32.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (2025.3.0)
Collecting cuda-bindings==12.9.4 (from torch>=1.6.0->ogb)
  Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.6.0->ogb) (1.5.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6.0->ogb) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.6.0->ogb) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->outdated>=0.2.0->ogb) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->outdated>=0.2.0->ogb) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->outdated>=0.2.0->ogb) (2026.2.25)
Downloading ogb-1.3.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 2.9 MB/s eta 0:00:00
Downloading outdated-0.2.2-py2.py3-none-any.whl (7.5 kB)
Downloading cuda_bindings-12.9.4-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 88.0 MB/s eta 0:00:00:00:01:01
Downloading littleutils-0.2.4-py3-none-any.whl (8.1 kB)
Installing collected packages: littleutils, cuda-bindings, outdated, ogb
  Attempting uninstall: cuda-bindings
    Found existing installation: cuda-bindings 13.2.0
    Uninstalling cuda-bindings-13.2.0:
      Successfully uninstalled cuda-bindings-13.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 26.2.0 requires cuda-core==0.3.*, but you have cuda-core 1.0.1 which is incompatible.
dask-cuda 26.2.0 requires numba-cuda<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
distributed-ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cuml-cu12 26.2.0 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cuml-cu12 26.2.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
ucxx-cu12 0.48.0 requires numba-cuda[cu12]<0.23.0,>=0.22.1, but you have numba-cuda 0.30.2 which is incompatible.
cudf-cu12 26.2.1 requires numba<0.62.0,>=0.60.0, but you have numba 0.65.1 which is incompatible.
cudf-cu12 26.2.1 requires numba-cuda[cu12]<0.23.0,>=0.22.2, but you have numba-cuda 0.30.2 which is incompatible.
Successfully installed cuda-bindings-12.9.4 littleutils-0.2.4 ogb-1.3.6 outdated-0.2.2
Collecting torch_geometric
  Downloading torch_geometric-2.8.0-py3-none-any.whl.metadata (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.13.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.4.6)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch_geometric) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch_geometric) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch_geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch_geometric) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch_geometric) (4.15.0)
Downloading torch_geometric-2.8.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 24.0 MB/s eta 0:00:00a 0:00:01
Installing collected packages: torch_geometric
Successfully installed torch_geometric-2.8.0

In [2]:

original_torch_load = torch.load

def patched_torch_load(*args, **kwargs):
    kwargs["weights_only"] = False
    return original_torch_load(*args, **kwargs)

torch.load = patched_torch_load

In [3]:
# loading the pre-saved dataset indices:

train_idx = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/ogbn-products-metadataokayy/Products_ogbn_train_index")
test_idx= torch.load(r"/kaggle/input/datasets/mehulgoyal1729/ogbn-products-metadataokayy/Products_ogbn_test_index")
valid_idx = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/ogbn-products-metadataokayy/Products_ogbn_valid_index")
labels_tensor = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/ogbn-products-metadataokayy/Products_ogbn_labels_tensor")
num_classes = 47
node_features = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/ogbn-products-metadataokayy/Products_ogbn_node_features")

torch.cuda.empty_cache()

## Testing with Simple Concatenation:

In [4]:
S = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/s-products-normed-k100/S_products_normed_k100")
S_given = node_features

In [5]:
node_features.shape

torch.Size([2449029, 100])

### MLP:

In [6]:
import torch
import torch.nn as nn
import torch.optim as optim
import copy
from torch.utils.data import TensorDataset, DataLoader

S = S.to(device)
S_given = S_given.to(device)

S_generated = torch.cat((S, S_given) , dim = 1)
del S, S_given

print(f"Shape of concatenated embeddings: {S_generated.shape}")

train_idx = torch.tensor(train_idx).to(device)
valid_idx =  torch.tensor(valid_idx).to(device)
test_idx  =  torch.tensor(test_idx).to(device)
labels_tensor = torch.tensor(labels_tensor).to(device) 


S_train = S_generated[train_idx].detach()
y_train = labels_tensor[train_idx].long()

S_valid = S_generated[valid_idx].detach()
y_valid = labels_tensor[valid_idx].long()

S_test  = S_generated[test_idx].detach()
y_test  = labels_tensor[test_idx].long()
del S_generated
print(f"Train nodes: {S_train.shape[0]} | Valid nodes: {S_valid.shape[0]} | Test nodes: {S_test.shape[0]}")

mean = S_train.mean(dim=0, keepdim=True)
std  = S_train.std(dim=0, keepdim=True) + 1e-7

S_train_scaled = (S_train - mean) / std
S_valid_scaled = (S_valid - mean) / std
S_test_scaled  = (S_test - mean) / std

batch_size = 2048
train_dataset = TensorDataset(S_train_scaled, y_train)
train_loader  = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden), 
            nn.ReLU(),
            nn.Dropout(0.5), 
            nn.Linear(hidden, hidden), 
            nn.ReLU(),
            nn.Dropout(0.5), 
            nn.Linear(hidden, out_dim)
        )
    def forward(self, x): return self.net(x)

K = S_train.shape[1]
model = MLP(K, 512, num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 200
losses = []
best_val_acc = 0.0
best_model_weights = None
patience = 20  
epochs_no_improve = 0
target_threshold = 0.99

for epoch in range(epochs):
    
    model.train()
    epoch_loss = 0.0
    
    for batch_x, batch_y in train_loader:
        optimizer.zero_grad()
        logits = model(batch_x)
        loss = criterion(logits, batch_y)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        
    avg_train_loss = epoch_loss / len(train_loader)
    losses.append(epoch_loss)
    
    model.eval()
    with torch.no_grad():
        val_logits = model(S_valid_scaled)
        val_preds = val_logits.argmax(dim=1)
        val_correct = (val_preds == y_valid).sum().item()
        val_acc = val_correct / len(y_valid)

    print(f'Epoch {epoch+1:3d}/{epochs} | Train Loss: {avg_train_loss:.4f} | Val Acc: {val_acc:.4f}')

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_model_weights = copy.deepcopy(model.state_dict())
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1

    if val_acc >= target_threshold:
        print(f"\nTarget Validation Accuracy ({target_threshold}) reached! Stopping early.")
        break
        
    if epochs_no_improve >= patience:
        print(f"\nEarly stopping triggered! No improvement for {patience} epochs.")
        break

print(f"\nLoading best model weights (Val Acc: {best_val_acc:.4f}) for Final Testing...")
model.load_state_dict(best_model_weights)


del S_train, S_valid

test_loader = DataLoader(
    TensorDataset(S_test_scaled, y_test),
    batch_size=4096,
    shuffle=False
)
from sklearn.metrics import classification_report, accuracy_score, f1_score

model.eval()

all_preds = []

with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        logits = model(batch_x)
        preds = logits.argmax(dim=1)
        all_preds.append(preds.cpu())

test_preds = torch.cat(all_preds)
test_correct = (test_preds == y_test.cpu()).sum().item()
test_acc = test_correct / len(y_test)

print(f"Final Test Accuracy: {test_acc:.4f}")
print(f"Final OGBN-Products Test Accuracy: {test_acc:.4f}")
print("\n--- MLP Classification Report ---")
print(classification_report(
    y_test.detach().cpu().numpy(),
    test_preds.detach().cpu().numpy(),
    digits=4
))

Shape of concatenated embeddings: torch.Size([2449029, 200])

/tmp/ipykernel_58/2423232819.py:18: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels_tensor).to(device)

Train nodes: 196615 | Valid nodes: 39323 | Test nodes: 2213091
Epoch   1/200 | Train Loss: 0.3441 | Val Acc: 0.8615
Epoch   2/200 | Train Loss: 0.0069 | Val Acc: 0.8565
Epoch   3/200 | Train Loss: 0.0029 | Val Acc: 0.8556
Epoch   4/200 | Train Loss: 0.0015 | Val Acc: 0.8552
Epoch   5/200 | Train Loss: 0.0015 | Val Acc: 0.8509
Epoch   6/200 | Train Loss: 0.0010 | Val Acc: 0.8536
Epoch   7/200 | Train Loss: 0.0003 | Val Acc: 0.8543
Epoch   8/200 | Train Loss: 0.0004 | Val Acc: 0.8554
Epoch   9/200 | Train Loss: 0.0004 | Val Acc: 0.8568
Epoch  10/200 | Train Loss: 0.0005 | Val Acc: 0.8504
Epoch  11/200 | Train Loss: 0.0003 | Val Acc: 0.8528
Epoch  12/200 | Train Loss: 0.0005 | Val Acc: 0.8511
Epoch  13/200 | Train Loss: 0.0004 | Val Acc: 0.8521
Epoch  14/200 | Train Loss: 0.0005 | Val Acc: 0.8555
Epoch  15/200 | Train Loss: 0.0005 | Val Acc: 0.8486
Epoch  16/200 | Train Loss: 0.0008 | Val Acc: 0.8513
Epoch  17/200 | Train Loss: 0.0005 | Val Acc: 0.8493
Epoch  18/200 | Train Loss: 0.0008 | Val Acc: 0.8570
Epoch  19/200 | Train Loss: 0.0006 | Val Acc: 0.8501
Epoch  20/200 | Train Loss: 0.0005 | Val Acc: 0.8545
Epoch  21/200 | Train Loss: 0.0002 | Val Acc: 0.8527

Early stopping triggered! No improvement for 20 epochs.

Loading best model weights (Val Acc: 0.8615) for Final Testing...
Final Test Accuracy: 0.7029
Final OGBN-Products Test Accuracy: 0.7029

--- MLP Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.6033    0.7441    0.6664    100670
           1     0.6224    0.7722    0.6893     95236
           2     0.8442    0.8438    0.8440    102870
           3     0.6467    0.6993    0.6720    135255
           4     0.8388    0.8469    0.8428    596195
           5     0.6625    0.8681    0.7515     35985
           6     0.6905    0.7533    0.7205    140356
           7     0.8366    0.9207    0.8766    152202
           8     0.7051    0.9397    0.8057     97679
           9     0.8685    0.8534    0.8609     59852
          10     0.6452    0.7626    0.6990     47165
          11     0.0946    0.3140    0.1454     28933
          12     0.7209    0.4827    0.5782    128632
          13     0.6808    0.7751    0.7249     88694
          14     0.1268    0.3639    0.1881      2734
          15     0.7674    0.8893    0.8239     23871
          16     0.7490    0.1678    0.2742     83019
          17     0.8561    0.8216    0.8385     37227
          18     0.7180    0.2451    0.3655     48228
          19     0.2014    0.3585    0.2579     15957
          20     0.6663    0.8833    0.7596     20090
          21     0.4597    0.2408    0.3161     79236
          22     0.8427    0.6010    0.7016       802
          23     0.1004    0.3302    0.1540      3047
          24     0.2914    0.0110    0.0212     45147
          25     0.4150    0.2088    0.2778      2912
          26     0.0000    0.0000    0.0000       472
          27     0.0000    0.0000    0.0000       254
          28     0.0016    0.0043    0.0023      1865
          29     0.5228    0.9017    0.6619      1373
          30     0.0000    0.0000    0.0000       257
          31     0.0000    0.0000    0.0000       388
          32     0.0000    0.0000    0.0000       470
          33     0.0000    0.0000    0.0000        25
          34     0.0000    0.0000    0.0000       152
          35     0.0000    0.0000    0.0000        36
          36     0.0000    0.0000    0.0000       628
          37     0.0000    0.0000    0.0000       511
          38     0.0000    0.0000    0.0000        90
          39     0.0000    0.0000    0.0000        36
          40     0.0000    0.0000    0.0000         5
          41     0.0000    0.0000    0.0000        60
          42     0.0000    0.0000    0.0000     32500
          43     0.0000    0.0000    0.0000      1399
          44     0.0000    0.0000    0.0000       566
          45     0.0000    0.0000    0.0000         9
          46     0.0000    0.0000    0.0000         1

    accuracy                         0.7029   2213091
   macro avg     0.3442    0.3533    0.3302   2213091
weighted avg     0.7076    0.7029    0.6870   2213091

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

### Multinomial Logistic Regressiom:

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, f1_score

S = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/s-products-normed-k100/S_products_normed_k100")
S_given = node_features

S = S.to(device)
S_given = S_given.to(device)

S_generated = torch.cat((S, S_given) , dim = 1)
del S, S_given

print(f"Shape of concatenated embeddings: {S_generated.shape}")

train_idx = torch.tensor(train_idx).to(device)
valid_idx =  torch.tensor(valid_idx).to(device)
test_idx  =  torch.tensor(test_idx).to(device)
labels_tensor = torch.tensor(labels_tensor).to(device) 


S_train = S_generated[train_idx].detach()
y_train = labels_tensor[train_idx].long()

S_valid = S_generated[valid_idx].detach()
y_valid = labels_tensor[valid_idx].long()

S_test  = S_generated[test_idx].detach()
y_test  = labels_tensor[test_idx].long()



print("\n--- Transferring Data to CPU for Scikit-Learn ---")
X_train_np = S_train.cpu().numpy()
y_train_np = y_train.cpu().numpy()

X_test_np  = S_test.cpu().numpy()
y_test_np  = y_test.cpu().numpy()

print("Training Logistic Regression...")
clf = LogisticRegression(max_iter=1000, multi_class='multinomial', n_jobs=-1)
clf.fit(X_train_np, y_train_np)

print("Evaluating on Test Set...")
y_pred = clf.predict(X_test_np)


print(f"Accuracy: {accuracy_score(y_pred,y_test_np )}")


print("\n--- Logistic Regression Classification Report ---")
print(classification_report(y_test_np, y_pred, digits=4))

Shape of concatenated embeddings: torch.Size([2449029, 200])

--- Transferring Data to CPU for Scikit-Learn ---

/tmp/ipykernel_58/311732516.py:15: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_idx = torch.tensor(train_idx).to(device)
/tmp/ipykernel_58/311732516.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  valid_idx =  torch.tensor(valid_idx).to(device)
/tmp/ipykernel_58/311732516.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_idx  =  torch.tensor(test_idx).to(device)
/tmp/ipykernel_58/311732516.py:18: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels_tensor).to(device)

Training Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Evaluating on Test Set...
Accuracy: 0.4760025683534929

--- Logistic Regression Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.3262    0.3939    0.3569    100670
           1     0.3903    0.3646    0.3770     95236
           2     0.6777    0.6542    0.6657    102870
           3     0.3162    0.4082    0.3564    135255
           4     0.4942    0.8458    0.6239    596195
           5     0.4075    0.2835    0.3344     35985
           6     0.3387    0.4304    0.3791    140356
           7     0.6035    0.5145    0.5555    152202
           8     0.6775    0.7559    0.7146     97679
           9     0.6806    0.4858    0.5670     59852
          10     0.3948    0.3369    0.3636     47165
          11     0.2243    0.0919    0.1304     28933
          12     0.5580    0.1990    0.2934    128632
          13     0.4303    0.2782    0.3379     88694
          14     0.3383    0.0753    0.1232      2734
          15     0.5750    0.2066    0.3040     23871
          16     0.7185    0.0251    0.0485     83019
          17     0.6564    0.3987    0.4961     37227
          18     0.3541    0.0048    0.0095     48228
          19     0.1545    0.0253    0.0435     15957
          20     0.3007    0.1906    0.2334     20090
          21     0.4516    0.0602    0.1062     79236
          22     0.0144    0.0050    0.0074       802
          23     0.1005    0.0876    0.0936      3047
          24     0.0245    0.0001    0.0002     45147
          25     0.0626    0.0124    0.0206      2912
          26     0.0000    0.0000    0.0000       472
          27     0.0535    0.0394    0.0454       254
          28     0.0000    0.0000    0.0000      1865
          29     0.0000    0.0000    0.0000      1373
          30     0.0000    0.0000    0.0000       257
          31     0.0030    0.0077    0.0043       388
          32     0.0000    0.0000    0.0000       470
          33     0.0000    0.0000    0.0000        25
          34     0.0000    0.0000    0.0000       152
          35     0.0472    0.1389    0.0704        36
          36     0.0000    0.0000    0.0000       628
          37     0.0000    0.0000    0.0000       511
          38     0.0000    0.0000    0.0000        90
          39     0.0000    0.0000    0.0000        36
          40     0.0000    0.0000    0.0000         5
          41     0.0000    0.0000    0.0000        60
          42     0.0000    0.0000    0.0000     32500
          43     0.0000    0.0000    0.0000      1399
          44     0.0000    0.0000    0.0000       566
          45     0.0000    0.0000    0.0000         9
          46     0.0000    0.0000    0.0000         1

    accuracy                         0.4760   2213091
   macro avg     0.2207    0.1558    0.1630   2213091
weighted avg     0.4676    0.4760    0.4281   2213091

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## CLIP based Contrastive Alignment :

### Contrastively Optiizing embeddings:

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import copy
import wandb 
from torch.utils.data import DataLoader, TensorDataset

# Encoding the Embeddings:
class Encoder(nn.Module):
    def __init__(self, input_dim=100, hidden_dim=256, latent_dim=128):
        super().__init__()
        self.encode_str = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, latent_dim)
        )
        self.encode_sem = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.BatchNorm1d(hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, latent_dim)
        )
        
        self.logit_scale = nn.Parameter(torch.ones([]) * np.log(1 / 0.07)) # temp scaling 

    def forward(self, x_str, x_sem):
        z_str = self.encode_str(x_str)
        z_sem = self.encode_sem(x_sem)

        z_str = F.normalize(z_str, p=2, dim=-1)
        z_sem = F.normalize(z_sem, p=2, dim=-1)

        return z_str, z_sem



# InfoNCE Constratsive Loss :
def infonce_loss(z_str, z_sem, logit_scale):
    logits_per_str = logit_scale.exp() * torch.matmul(z_str, z_sem.t())
    logits_per_sem = logits_per_str.t() 

    batch_size = z_str.shape[0]
    labels = torch.arange(batch_size, dtype=torch.long, device=z_str.device)

    loss_str = F.cross_entropy(logits_per_str, labels)
    loss_sem = F.cross_entropy(logits_per_sem, labels)

    return (loss_str + loss_sem) / 2

S = S.to(device)
S_given = S_given.to(device)

print("\n--- Standardizing Tensors ---")
mean_S = S.mean(dim=0, keepdim=True)
std_S = S.std(dim=0, keepdim=True) + 1e-7
S_scaled = (S - mean_S) / std_S

mean_S_given = S_given.mean(dim=0, keepdim=True)
std_S_given = S_given.std(dim=0, keepdim=True) + 1e-7
S_given_scaled = (S_given - mean_S_given) / std_S_given

batch_size = 4096 
dataset = TensorDataset(S_scaled, S_given_scaled) 
loader = DataLoader(dataset, batch_size=batch_size, shuffle=True, drop_last=True)




config = {
    "input_dim": 100,
    "hidden_dim": 512,
    "latent_dim": 128,
    "batch_size": batch_size,
    "learning_rate": 0.01,
    "weight_decay": 1e-4,
    "epochs": 1000,
    "patience": 10
}

wandb.init(
    project="fuse-ogbn-products-contrastive",
    name="latent-alignment-infonce",
    config=config
)

model = Encoder(
    input_dim=config["input_dim"], 
    hidden_dim=config["hidden_dim"], 
    latent_dim=config["latent_dim"]
).to(device)

optimizer = optim.Adam(model.parameters(), lr=config["learning_rate"], weight_decay=config["weight_decay"])
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=20, gamma=0.9)

print("\n--- Starting Contrastive Latent Alignment ---")

best_loss = float('inf')
epochs_no_improve = 0
best_model_weights = copy.deepcopy(model.state_dict())

for epoch in range(config["epochs"]):
    model.train()
    total_loss = 0.0
    
    total_top1_acc = 0.0
    total_pos_sim = 0.0
    total_neg_sim = 0.0
    
    for batch_str, batch_sem in loader:
        optimizer.zero_grad()
        
        z_str, z_sem = model(batch_str, batch_sem)
        loss = infonce_loss(z_str, z_sem, model.logit_scale)
        
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
        
        
        with torch.no_grad():
            raw_sim = torch.matmul(z_str, z_sem.t())
            curr_batch_size = raw_sim.shape[0]
            labels = torch.arange(curr_batch_size, device=raw_sim.device)
            
            preds = raw_sim.argmax(dim=1)
            acc = (preds == labels).float().mean().item()
            total_top1_acc += acc
            
            pos_sim = torch.diag(raw_sim).mean().item()
            total_pos_sim += pos_sim
            
            sum_all = raw_sim.sum().item()
            sum_pos = torch.diag(raw_sim).sum().item()
            neg_sim = (sum_all - sum_pos) / (curr_batch_size * (curr_batch_size - 1))
            total_neg_sim += neg_sim
            
    
    num_batches = len(loader)
    avg_loss = total_loss / num_batches
    avg_top1 = total_top1_acc / num_batches
    avg_pos = total_pos_sim / num_batches
    avg_neg = total_neg_sim / num_batches
    
    current_temp = model.logit_scale.exp().item()
    
    scheduler.step()

    wandb.log({
        "epoch": epoch + 1,
        "InfoNCE_Loss": avg_loss,
        "Top1_Accuracy_Pct": avg_top1 * 100,
        "Pos_Similarity": avg_pos,
        "Neg_Similarity": avg_neg,
        "Temp_Scale": current_temp,
        "Learning_Rate": optimizer.param_groups[0]['lr']
    })

    if avg_loss < best_loss - 1e-3:
        best_loss = avg_loss
        epochs_no_improve = 0
        best_model_weights = copy.deepcopy(model.state_dict())
    else:
        epochs_no_improve += 1

    if (epoch + 1) % 1 == 0 or epoch == 0:
        print(f"Epoch {epoch+1:3d}/{config['epochs']} | Loss: {avg_loss:.4f} | "
              f"Top-1 Acc: {avg_top1*100:.1f}% | "
              f"Pos Sim: {avg_pos:.3f} | Neg Sim: {avg_neg:.3f} | "
              f"Temp: {current_temp:.1f}")



    if epoch == 50:
        break
    if epochs_no_improve >= config["patience"]:
        print(f"\nEarly stopping triggered! No improvement in loss for {config['patience']} epochs.")
        break

print("Contrastive Alignment Complete.")

# 
print(f"\nLoading best model weights (Loss: {best_loss:.4f}) for extraction...")
model.load_state_dict(best_model_weights)
model.eval()

final_dataset = TensorDataset(S_scaled, S_given_scaled)
final_loader = DataLoader(final_dataset, batch_size=4096, shuffle=False)

all_z_str = []
all_z_sem = []

with torch.no_grad():
    for batch_str, batch_sem in final_loader:
        batch_z_str, batch_z_sem = model(batch_str, batch_sem)

        all_z_str.append(batch_z_str.cpu())
        all_z_sem.append(batch_z_sem.cpu())

Final_Z_str = torch.cat(all_z_str, dim=0)
Final_Z_sem = torch.cat(all_z_sem, dim=0)

Z_fused = Final_Z_str + Final_Z_sem

print(f"Final Fused Embedding Matrix Shape: {Z_fused.shape}")

wandb.finish()

--- Standardizing Tensors ---

--- Starting Contrastive Latent Alignment ---
Epoch   1/1000 | Loss: 6.6290 | Top-1 Acc: 2.0% | Pos Sim: 0.529 | Neg Sim: 0.297 | Temp: 18.0
Epoch   2/1000 | Loss: 6.2198 | Top-1 Acc: 3.7% | Pos Sim: 0.447 | Neg Sim: 0.218 | Temp: 20.7
Epoch   3/1000 | Loss: 6.1434 | Top-1 Acc: 4.2% | Pos Sim: 0.418 | Neg Sim: 0.203 | Temp: 21.3
Epoch   4/1000 | Loss: 6.1094 | Top-1 Acc: 4.4% | Pos Sim: 0.404 | Neg Sim: 0.194 | Temp: 21.9
Epoch   5/1000 | Loss: 6.0913 | Top-1 Acc: 4.6% | Pos Sim: 0.397 | Neg Sim: 0.190 | Temp: 22.5
Epoch   6/1000 | Loss: 6.0832 | Top-1 Acc: 4.7% | Pos Sim: 0.392 | Neg Sim: 0.186 | Temp: 22.5
Epoch   7/1000 | Loss: 6.0751 | Top-1 Acc: 4.7% | Pos Sim: 0.391 | Neg Sim: 0.186 | Temp: 22.6
Epoch   8/1000 | Loss: 6.0708 | Top-1 Acc: 4.7% | Pos Sim: 0.389 | Neg Sim: 0.185 | Temp: 22.7
Epoch   9/1000 | Loss: 6.0667 | Top-1 Acc: 4.8% | Pos Sim: 0.389 | Neg Sim: 0.184 | Temp: 22.7
Epoch  10/1000 | Loss: 6.0625 | Top-1 Acc: 4.8% | Pos Sim: 0.388 | Neg Sim: 0.183 | Temp: 22.7
Epoch  11/1000 | Loss: 6.0605 | Top-1 Acc: 4.8% | Pos Sim: 0.387 | Neg Sim: 0.182 | Temp: 22.6
Epoch  12/1000 | Loss: 6.0578 | Top-1 Acc: 4.8% | Pos Sim: 0.386 | Neg Sim: 0.181 | Temp: 22.7
Epoch  13/1000 | Loss: 6.0574 | Top-1 Acc: 4.8% | Pos Sim: 0.386 | Neg Sim: 0.181 | Temp: 22.6
Epoch  14/1000 | Loss: 6.0565 | Top-1 Acc: 4.8% | Pos Sim: 0.386 | Neg Sim: 0.182 | Temp: 22.6
Epoch  15/1000 | Loss: 6.0564 | Top-1 Acc: 4.8% | Pos Sim: 0.385 | Neg Sim: 0.180 | Temp: 22.7
Epoch  16/1000 | Loss: 6.0534 | Top-1 Acc: 4.9% | Pos Sim: 0.385 | Neg Sim: 0.181 | Temp: 22.8
Epoch  17/1000 | Loss: 6.0534 | Top-1 Acc: 4.9% | Pos Sim: 0.385 | Neg Sim: 0.180 | Temp: 22.8
Epoch  18/1000 | Loss: 6.0521 | Top-1 Acc: 4.9% | Pos Sim: 0.384 | Neg Sim: 0.180 | Temp: 22.7
Epoch  19/1000 | Loss: 6.0518 | Top-1 Acc: 4.9% | Pos Sim: 0.384 | Neg Sim: 0.179 | Temp: 22.8
Epoch  20/1000 | Loss: 6.0515 | Top-1 Acc: 4.9% | Pos Sim: 0.384 | Neg Sim: 0.179 | Temp: 22.9
Epoch  21/1000 | Loss: 6.0335 | Top-1 Acc: 4.9% | Pos Sim: 0.383 | Neg Sim: 0.178 | Temp: 22.9
Epoch  22/1000 | Loss: 6.0310 | Top-1 Acc: 5.0% | Pos Sim: 0.382 | Neg Sim: 0.178 | Temp: 23.0
Epoch  23/1000 | Loss: 6.0325 | Top-1 Acc: 5.0% | Pos Sim: 0.381 | Neg Sim: 0.178 | Temp: 23.1
Epoch  24/1000 | Loss: 6.0301 | Top-1 Acc: 5.0% | Pos Sim: 0.380 | Neg Sim: 0.177 | Temp: 23.0
Epoch  25/1000 | Loss: 6.0283 | Top-1 Acc: 5.0% | Pos Sim: 0.380 | Neg Sim: 0.177 | Temp: 23.4
Epoch  26/1000 | Loss: 6.0294 | Top-1 Acc: 5.0% | Pos Sim: 0.380 | Neg Sim: 0.177 | Temp: 23.1
Epoch  27/1000 | Loss: 6.0281 | Top-1 Acc: 5.0% | Pos Sim: 0.380 | Neg Sim: 0.177 | Temp: 22.9
Epoch  28/1000 | Loss: 6.0263 | Top-1 Acc: 5.0% | Pos Sim: 0.379 | Neg Sim: 0.177 | Temp: 23.3
Epoch  29/1000 | Loss: 6.0269 | Top-1 Acc: 5.0% | Pos Sim: 0.380 | Neg Sim: 0.177 | Temp: 23.2
Epoch  30/1000 | Loss: 6.0269 | Top-1 Acc: 5.0% | Pos Sim: 0.378 | Neg Sim: 0.176 | Temp: 23.5
Epoch  31/1000 | Loss: 6.0261 | Top-1 Acc: 5.0% | Pos Sim: 0.379 | Neg Sim: 0.177 | Temp: 23.2
Epoch  32/1000 | Loss: 6.0260 | Top-1 Acc: 5.0% | Pos Sim: 0.379 | Neg Sim: 0.176 | Temp: 23.1
Epoch  33/1000 | Loss: 6.0261 | Top-1 Acc: 5.0% | Pos Sim: 0.379 | Neg Sim: 0.176 | Temp: 23.3
Epoch  34/1000 | Loss: 6.0255 | Top-1 Acc: 5.0% | Pos Sim: 0.378 | Neg Sim: 0.176 | Temp: 23.2
Epoch  35/1000 | Loss: 6.0252 | Top-1 Acc: 5.0% | Pos Sim: 0.378 | Neg Sim: 0.175 | Temp: 23.3
Epoch  36/1000 | Loss: 6.0257 | Top-1 Acc: 5.0% | Pos Sim: 0.378 | Neg Sim: 0.176 | Temp: 23.1
Epoch  37/1000 | Loss: 6.0243 | Top-1 Acc: 5.1% | Pos Sim: 0.378 | Neg Sim: 0.175 | Temp: 23.4
Epoch  38/1000 | Loss: 6.0257 | Top-1 Acc: 5.1% | Pos Sim: 0.378 | Neg Sim: 0.176 | Temp: 23.3
Epoch  39/1000 | Loss: 6.0254 | Top-1 Acc: 5.0% | Pos Sim: 0.377 | Neg Sim: 0.175 | Temp: 23.4
Epoch  40/1000 | Loss: 6.0247 | Top-1 Acc: 5.1% | Pos Sim: 0.377 | Neg Sim: 0.176 | Temp: 23.3
Epoch  41/1000 | Loss: 6.0086 | Top-1 Acc: 5.1% | Pos Sim: 0.376 | Neg Sim: 0.175 | Temp: 23.7
Epoch  42/1000 | Loss: 6.0079 | Top-1 Acc: 5.1% | Pos Sim: 0.375 | Neg Sim: 0.175 | Temp: 23.7
Epoch  43/1000 | Loss: 6.0069 | Top-1 Acc: 5.2% | Pos Sim: 0.375 | Neg Sim: 0.174 | Temp: 23.8
Epoch  44/1000 | Loss: 6.0042 | Top-1 Acc: 5.2% | Pos Sim: 0.374 | Neg Sim: 0.174 | Temp: 23.8
Epoch  45/1000 | Loss: 6.0041 | Top-1 Acc: 5.2% | Pos Sim: 0.374 | Neg Sim: 0.173 | Temp: 23.9
Epoch  46/1000 | Loss: 6.0039 | Top-1 Acc: 5.2% | Pos Sim: 0.374 | Neg Sim: 0.173 | Temp: 23.6
Epoch  47/1000 | Loss: 6.0040 | Top-1 Acc: 5.2% | Pos Sim: 0.374 | Neg Sim: 0.173 | Temp: 23.8
Epoch  48/1000 | Loss: 6.0040 | Top-1 Acc: 5.2% | Pos Sim: 0.373 | Neg Sim: 0.173 | Temp: 23.8
Epoch  49/1000 | Loss: 6.0021 | Top-1 Acc: 5.2% | Pos Sim: 0.373 | Neg Sim: 0.173 | Temp: 23.7
Epoch  50/1000 | Loss: 6.0035 | Top-1 Acc: 5.2% | Pos Sim: 0.373 | Neg Sim: 0.173 | Temp: 23.7
Epoch  51/1000 | Loss: 6.0029 | Top-1 Acc: 5.2% | Pos Sim: 0.374 | Neg Sim: 0.173 | Temp: 23.7
Contrastive Alignment Complete.

Loading best model weights (Loss: 6.0021) for extraction...
Final Fused Embedding Matrix Shape: torch.Size([2449029, 128])

In [ ]:
clip_fused = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/clipproducts/Clip_Products.pth")

In [18]:
torch.save(Z_fused, "Clip_Products_new.pth")

In [12]:
S_generated = clip_fused

In [13]:
train_idx = torch.tensor(train_idx).to(device)
valid_idx = torch.tensor(valid_idx).to(device)
test_idx  = torch.tensor(test_idx).to(device)
labels_tensor = torch.tensor(labels_tensor).to(device)
S_generated = S_generated.to(device)



print(S_generated.device)
print(train_idx.device)

S_train = S_generated[train_idx].detach()
y_train = labels_tensor[train_idx].long()

S_valid = S_generated[valid_idx].detach()
y_valid = labels_tensor[valid_idx].long()

S_test = S_generated[test_idx].detach()
y_test = labels_tensor[test_idx].long()

/tmp/ipykernel_58/1200573675.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_idx = torch.tensor(train_idx).to(device)
/tmp/ipykernel_58/1200573675.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  valid_idx = torch.tensor(valid_idx).to(device)
/tmp/ipykernel_58/1200573675.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_idx  = torch.tensor(test_idx).to(device)
/tmp/ipykernel_58/1200573675.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels_tensor).to(device)

cuda:0
cuda:0

### MLP

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim
import copy
from torch.utils.data import TensorDataset, DataLoader

S_generated = clip_fused

print(f"Shape of concatenated embeddings: {S_generated.shape}")

train_idx = torch.tensor(train_idx).to(device)
valid_idx = torch.tensor(valid_idx).to(device)
test_idx  = torch.tensor(test_idx).to(device)
labels_tensor = torch.tensor(labels_tensor).to(device)
S_generated = S_generated.to(device)



print(S_generated.device)
print(train_idx.device)

S_train = S_generated[train_idx].detach()
y_train = labels_tensor[train_idx].long()

S_valid = S_generated[valid_idx].detach()
y_valid = labels_tensor[valid_idx].long()

S_test = S_generated[test_idx].detach()
y_test = labels_tensor[test_idx].long()

del S_generated

print(
    f"Train nodes: {S_train.shape[0]} | "
    f"Valid nodes: {S_valid.shape[0]} | "
    f"Test nodes: {S_test.shape[0]}"
)

mean = S_train.mean(dim=0, keepdim=True)
std = S_train.std(dim=0, keepdim=True) + 1e-7

S_train_scaled = (S_train - mean) / std
S_valid_scaled = (S_valid - mean) / std
S_test_scaled  = (S_test - mean) / std

batch_size = 2048

train_dataset = TensorDataset(S_train_scaled, y_train)
train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True
)

class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.BatchNorm1d(hidden),   
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(hidden, hidden),
            nn.BatchNorm1d(hidden),  
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(hidden, out_dim)
        )

    def forward(self, x):
        return self.net(x)

K = S_train.shape[1]

model = MLP(K, 512, num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 200
best_val_acc = 0
best_model_weights = None

patience = 20
epochs_no_improve = 0
target_threshold = 0.99

for epoch in range(epochs):


    model.train()

    epoch_loss = 0

    for batch_x, batch_y in train_loader:

        optimizer.zero_grad()

        logits = model(batch_x)

        loss = criterion(logits, batch_y)

        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()

    avg_train_loss = epoch_loss / len(train_loader)


    model.eval()

    with torch.no_grad():

        train_logits = model(S_train_scaled)
        train_preds = train_logits.argmax(dim=1)

        train_correct = (
            train_preds == y_train
        ).sum().item()

        train_acc = train_correct / len(y_train)

        val_logits = model(S_valid_scaled)

        val_preds = val_logits.argmax(dim=1)

        val_correct = (
            val_preds == y_valid
        ).sum().item()

        val_acc = val_correct / len(y_valid)

    gap = train_acc - val_acc

    print(
        f"Epoch {epoch+1:3d}/{epochs} | "
        f"Loss: {avg_train_loss:.4f} | "
        f"Train Acc: {train_acc:.4f} | "
        f"Val Acc: {val_acc:.4f} | "
        f"Gap: {gap:.4f}"
    )

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_model_weights = copy.deepcopy(
            model.state_dict()
        )
        epochs_no_improve = 0

    else:
        epochs_no_improve += 1

    if val_acc >= target_threshold:
        print(
            f"\nTarget validation accuracy "
            f"{target_threshold} reached."
        )
        break

    if epochs_no_improve >= patience:
        print(
            f"\nEarly stopping "
            f"(no improvement for {patience} epochs)"
        )
        break

print(
    f"\nLoading best model "
    f"(Val Acc={best_val_acc:.4f})"
)

model.load_state_dict(best_model_weights)

test_loader = DataLoader(
    TensorDataset(S_test_scaled, y_test),
    batch_size=4096,
    shuffle=False
)

model.eval()

all_preds = []

with torch.no_grad():

    for batch_x, _ in test_loader:

        logits = model(batch_x)

        preds = logits.argmax(dim=1)

        all_preds.append(
            preds.cpu()
        )

test_preds = torch.cat(all_preds)

test_acc = (
    (test_preds == y_test.cpu())
    .sum()
    .item()
    / len(y_test)
)

print(f"Final Test Accuracy: {test_acc:.4f}")

from sklearn.metrics import classification_report, confusion_matrix

from sklearn.metrics import classification_report

print("\n--- Classification Report ---")
print(
    classification_report(
        y_test.cpu().numpy(),
        test_preds.numpy(),
        digits=4
    )
)

Shape of concatenated embeddings: torch.Size([2449029, 128])

/tmp/ipykernel_58/2128991963.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_idx = torch.tensor(train_idx).to(device)
/tmp/ipykernel_58/2128991963.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  valid_idx = torch.tensor(valid_idx).to(device)
/tmp/ipykernel_58/2128991963.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_idx  = torch.tensor(test_idx).to(device)
/tmp/ipykernel_58/2128991963.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels_tensor).to(device)

cuda:0
cuda:0
Train nodes: 196615 | Valid nodes: 39323 | Test nodes: 2213091
Epoch   1/200 | Loss: 0.2907 | Train Acc: 0.9980 | Val Acc: 0.8143 | Gap: 0.1837
Epoch   2/200 | Loss: 0.0190 | Train Acc: 0.9989 | Val Acc: 0.8142 | Gap: 0.1847
Epoch   3/200 | Loss: 0.0093 | Train Acc: 0.9993 | Val Acc: 0.8126 | Gap: 0.1867
Epoch   4/200 | Loss: 0.0071 | Train Acc: 0.9996 | Val Acc: 0.8089 | Gap: 0.1907
Epoch   5/200 | Loss: 0.0049 | Train Acc: 0.9997 | Val Acc: 0.8056 | Gap: 0.1941
Epoch   6/200 | Loss: 0.0035 | Train Acc: 0.9998 | Val Acc: 0.8003 | Gap: 0.1995
Epoch   7/200 | Loss: 0.0027 | Train Acc: 0.9999 | Val Acc: 0.8008 | Gap: 0.1990
Epoch   8/200 | Loss: 0.0023 | Train Acc: 0.9999 | Val Acc: 0.7946 | Gap: 0.2052
Epoch   9/200 | Loss: 0.0019 | Train Acc: 0.9999 | Val Acc: 0.7899 | Gap: 0.2100
Epoch  10/200 | Loss: 0.0018 | Train Acc: 0.9999 | Val Acc: 0.7955 | Gap: 0.2044
Epoch  11/200 | Loss: 0.0018 | Train Acc: 0.9999 | Val Acc: 0.7995 | Gap: 0.2004
Epoch  12/200 | Loss: 0.0019 | Train Acc: 0.9999 | Val Acc: 0.7937 | Gap: 0.2063
Epoch  13/200 | Loss: 0.0014 | Train Acc: 0.9999 | Val Acc: 0.7932 | Gap: 0.2067
Epoch  14/200 | Loss: 0.0015 | Train Acc: 0.9999 | Val Acc: 0.7875 | Gap: 0.2124
Epoch  15/200 | Loss: 0.0018 | Train Acc: 0.9999 | Val Acc: 0.7933 | Gap: 0.2066
Epoch  16/200 | Loss: 0.0013 | Train Acc: 0.9999 | Val Acc: 0.7934 | Gap: 0.2065
Epoch  17/200 | Loss: 0.0114 | Train Acc: 1.0000 | Val Acc: 0.7922 | Gap: 0.2077
Epoch  18/200 | Loss: 0.0038 | Train Acc: 1.0000 | Val Acc: 0.7981 | Gap: 0.2018
Epoch  19/200 | Loss: 0.0018 | Train Acc: 1.0000 | Val Acc: 0.7981 | Gap: 0.2018
Epoch  20/200 | Loss: 0.0017 | Train Acc: 1.0000 | Val Acc: 0.7922 | Gap: 0.2078
Epoch  21/200 | Loss: 0.0016 | Train Acc: 1.0000 | Val Acc: 0.7939 | Gap: 0.2061

Early stopping (no improvement for 20 epochs)

Loading best model (Val Acc=0.8143)
Final Test Accuracy: 0.6941

--- Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.5189    0.7278    0.6059    100670
           1     0.5771    0.6909    0.6289     95236
           2     0.7516    0.8809    0.8111    102870
           3     0.5846    0.4332    0.4976    135255
           4     0.8503    0.8657    0.8579    596195
           5     0.6102    0.8429    0.7079     35985
           6     0.6960    0.5184    0.5943    140356
           7     0.7941    0.9240    0.8541    152202
           8     0.7150    0.9533    0.8171     97679
           9     0.8486    0.8324    0.8404     59852
          10     0.6882    0.6977    0.6929     47165
          11     0.3147    0.4484    0.3698     28933
          12     0.7411    0.5673    0.6427    128632
          13     0.7571    0.6517    0.7004     88694
          14     0.4075    0.4473    0.4265      2734
          15     0.5693    0.9362    0.7080     23871
          16     0.5657    0.4144    0.4784     83019
          17     0.7741    0.9229    0.8420     37227
          18     0.4708    0.4309    0.4500     48228
          19     0.2151    0.4763    0.2964     15957
          20     0.5174    0.8852    0.6531     20090
          21     0.4868    0.3311    0.3941     79236
          22     0.0000    0.0000    0.0000       802
          23     0.0566    0.5307    0.1023      3047
          24     0.8694    0.0090    0.0178     45147
          25     0.7356    0.1271    0.2167      2912
          26     0.0000    0.0000    0.0000       472
          27     0.0000    0.0000    0.0000       254
          28     0.0000    0.0000    0.0000      1865
          29     0.9728    0.8325    0.8972      1373
          30     0.0000    0.0000    0.0000       257
          31     0.0000    0.0000    0.0000       388
          32     0.0000    0.0000    0.0000       470
          33     0.0000    0.0000    0.0000        25
          34     0.0000    0.0000    0.0000       152
          35     0.0000    0.0000    0.0000        36
          36     0.0000    0.0000    0.0000       628
          37     0.0000    0.0000    0.0000       511
          38     0.0000    0.0000    0.0000        90
          39     0.0000    0.0000    0.0000        36
          40     0.0000    0.0000    0.0000         5
          41     0.0000    0.0000    0.0000        60
          42     0.0000    0.0000    0.0000     32500
          43     0.0000    0.0000    0.0000      1399
          44     0.0000    0.0000    0.0000       566
          45     0.0000    0.0000    0.0000         9
          46     0.0000    0.0000    0.0000         1

    accuracy                         0.6941   2213091
   macro avg     0.3423    0.3485    0.3214   2213091
weighted avg     0.6977    0.6941    0.6792   2213091

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [16]:
S_generated = clip_fused

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, f1_score



train_idx = torch.tensor(train_idx).to(device)
valid_idx =  torch.tensor(valid_idx).to(device)
test_idx  =  torch.tensor(test_idx).to(device)
labels_tensor = torch.tensor(labels_tensor).to(device) 

S_generated = S_generated.to(device)

S_train = S_generated[train_idx].detach()
y_train = labels_tensor[train_idx].long()

S_valid = S_generated[valid_idx].detach()
y_valid = labels_tensor[valid_idx].long()

S_test  = S_generated[test_idx].detach()
y_test  = labels_tensor[test_idx].long()



print("\n--- Transferring Data to CPU for Scikit-Learn ---")
X_train_np = S_train.cpu().numpy()
y_train_np = y_train.cpu().numpy()

X_test_np  = S_test.cpu().numpy()
y_test_np  = y_test.cpu().numpy()

print("Training Logistic Regression...")
clf = LogisticRegression(max_iter=1000, multi_class='multinomial', n_jobs=-1)
clf.fit(X_train_np, y_train_np)

print("Evaluating on Test Set...")
y_pred = clf.predict(X_test_np)


print(f"Accuracy: {accuracy_score(y_pred,y_test_np )}")


print("\n--- Logistic Regression Classification Report ---")
print(classification_report(y_test_np, y_pred, digits=4))

/tmp/ipykernel_58/3732168673.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_idx = torch.tensor(train_idx).to(device)
/tmp/ipykernel_58/3732168673.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  valid_idx =  torch.tensor(valid_idx).to(device)
/tmp/ipykernel_58/3732168673.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_idx  =  torch.tensor(test_idx).to(device)
/tmp/ipykernel_58/3732168673.py:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_tensor = torch.tensor(labels_tensor).to(device)

--- Transferring Data to CPU for Scikit-Learn ---
Training Logistic Regression...

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Evaluating on Test Set...
Accuracy: 0.7632804073578537

--- Logistic Regression Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.6772    0.7951    0.7314    100670
           1     0.6954    0.7543    0.7237     95236
           2     0.8932    0.8344    0.8628    102870
           3     0.7560    0.6189    0.6806    135255
           4     0.9289    0.8800    0.9038    596195
           5     0.6635    0.8536    0.7466     35985
           6     0.7338    0.7904    0.7611    140356
           7     0.7758    0.9588    0.8577    152202
           8     0.7841    0.9614    0.8638     97679
           9     0.8736    0.8919    0.8826     59852
          10     0.6468    0.8230    0.7243     47165
          11     0.3140    0.4978    0.3851     28933
          12     0.8487    0.6206    0.7170    128632
          13     0.7508    0.7800    0.7651     88694
          14     0.3449    0.4682    0.3972      2734
          15     0.6962    0.9353    0.7982     23871
          16     0.6737    0.6600    0.6668     83019
          17     0.8497    0.9248    0.8856     37227
          18     0.6847    0.5206    0.5914     48228
          19     0.2961    0.4377    0.3532     15957
          20     0.6467    0.8947    0.7507     20090
          21     0.5914    0.4773    0.5283     79236
          22     0.1141    0.6571    0.1945       802
          23     0.0569    0.5579    0.1033      3047
          24     0.5964    0.0110    0.0215     45147
          25     0.6323    0.4069    0.4952      2912
          26     0.0119    0.0424    0.0186       472
          27     0.0000    0.0000    0.0000       254
          28     0.0147    0.0601    0.0236      1865
          29     0.8679    0.9141    0.8904      1373
          30     0.0000    0.0000    0.0000       257
          31     0.0000    0.0000    0.0000       388
          32     0.0045    0.0106    0.0063       470
          33     0.0000    0.0000    0.0000        25
          34     0.0000    0.0000    0.0000       152
          35     0.3889    0.3889    0.3889        36
          36     0.0000    0.0000    0.0000       628
          37     0.0000    0.0000    0.0000       511
          38     0.0000    0.0000    0.0000        90
          39     0.0000    0.0000    0.0000        36
          40     0.0000    0.0000    0.0000         5
          41     0.0000    0.0000    0.0000        60
          42     0.0000    0.0000    0.0000     32500
          43     0.0000    0.0000    0.0000      1399
          44     0.0000    0.0000    0.0000       566
          45     0.0000    0.0000    0.0000         9
          46     0.0000    0.0000    0.0000         1

    accuracy                         0.7633   2213091
   macro avg     0.3790    0.4134    0.3770   2213091
weighted avg     0.7702    0.7633    0.7558   2213091

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## 30-70 Dataset Split Evaluation for Late Fusion

### Testing the Fusion techniques on 30-70 MCAR split :

In [18]:

seed = 42
mask_frac = 0.70 

labels_for_split = torch.as_tensor(labels_tensor).long().view(-1).cpu()
classes = torch.unique(labels_for_split)

generator_cpu = torch.Generator(device='cpu')
generator_cpu.manual_seed(seed)

mask_idx_list = []
labeled_idx_list = []

for c in classes:
    c_indices = (labels_for_split == c).nonzero(as_tuple=True)[0]

    num_in_class = c_indices.size(0)
    num_mask_c = int(mask_frac * num_in_class)

    perm = torch.randperm(num_in_class, generator=generator_cpu)

    mask_idx_list.append(c_indices[perm[:num_mask_c]])
    labeled_idx_list.append(c_indices[perm[num_mask_c:]])

test_idx_30_70 = torch.cat(mask_idx_list)
train_idx_30_70 = torch.cat(labeled_idx_list)

train_idx_30_70 = train_idx_30_70[torch.randperm(train_idx_30_70.numel(), generator=generator_cpu)]
test_idx_30_70 = test_idx_30_70[torch.randperm(test_idx_30_70.numel(), generator=generator_cpu)]

print("--- 30-70 Dataset Split ---")
print(f"Total nodes: {labels_for_split.numel()}")
print(f"Train nodes: {train_idx_30_70.numel()} ({train_idx_30_70.numel()/labels_for_split.numel():.2%})")
print(f"Test nodes:  {test_idx_30_70.numel()} ({test_idx_30_70.numel()/labels_for_split.numel():.2%})")

train_class_counts = torch.bincount(labels_for_split[train_idx_30_70], minlength=num_classes)
test_class_counts = torch.bincount(labels_for_split[test_idx_30_70], minlength=num_classes)

print(f"Classes present in train: {(train_class_counts > 0).sum().item()} / {num_classes}")
print(f"Classes present in test:  {(test_class_counts > 0).sum().item()} / {num_classes}")

--- 30-70 Dataset Split ---
Total nodes: 2449029
Train nodes: 734732 (30.00%)
Test nodes:  1714297 (70.00%)
Classes present in train: 47 / 47
Classes present in test:  46 / 47

In [ ]:


import torch
import torch.nn as nn
import torch.optim as optim
import copy
import pandas as pd
from torch.utils.data import TensorDataset, DataLoader
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, f1_score

late_fusion_30_70_results = []

class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden),
            nn.BatchNorm1d(hidden),
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(hidden, hidden),
            nn.BatchNorm1d(hidden),
            nn.ReLU(),
            nn.Dropout(0.5),

            nn.Linear(hidden, out_dim)
        )

    def forward(self, x):
        return self.net(x)


def predict_in_batches(model, X, batch_size=16384):
    model.eval()
    preds = []

    with torch.no_grad():
        for start in range(0, X.shape[0], batch_size):
            end = start + batch_size
            batch_x = X[start:end].to(device)
            logits = model(batch_x)
            preds.append(logits.argmax(dim=1).cpu())

    return torch.cat(preds, dim=0)


def evaluate_late_fusion_30_70(
    S_eval,
    labels_eval,
    train_idx_eval,
    test_idx_eval,
    fusion_name,
    hidden_dim=512,
    batch_size=4096,
    epochs=200,
    patience=10,
    valid_ratio=0.10
):
    print("\n" + "=" * 80)
    print(f"30-70 Split Evaluation: {fusion_name}")
    print("=" * 80)

    S_eval = S_eval.detach().float().cpu()
    labels_eval = torch.as_tensor(labels_eval).long().view(-1).cpu()

    X_train = S_eval[train_idx_eval].detach()
    y_train = labels_eval[train_idx_eval].detach().long()

    X_test = S_eval[test_idx_eval].detach()
    y_test = labels_eval[test_idx_eval].detach().long()

    print(f"Train nodes: {X_train.shape[0]} | Test nodes: {X_test.shape[0]}")
    print(f"Embedding dimension: {X_train.shape[1]}")

    mean = X_train.mean(dim=0, keepdim=True)
    std = X_train.std(dim=0, keepdim=True) + 1e-7

    X_train_scaled = (X_train - mean) / std
    X_test_scaled = (X_test - mean) / std


    train_count = X_train_scaled.shape[0]
    internal_val_count = max(num_classes, int(valid_ratio * train_count))

    inner_perm_cpu = torch.randperm(train_count, generator=generator_cpu)
    inner_val_pos = inner_perm_cpu[:internal_val_count]
    inner_train_pos = inner_perm_cpu[internal_val_count:]

    X_inner_train = X_train_scaled[inner_train_pos]
    y_inner_train = y_train[inner_train_pos]

    X_inner_val = X_train_scaled[inner_val_pos]
    y_inner_val = y_train[inner_val_pos]

    train_dataset = TensorDataset(X_inner_train, y_inner_train)
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True
    )

    # ------------------------------------------------------------
    # MLP evaluation
    # ------------------------------------------------------------
    print("\n--- Training MLP on 30% train nodes ---")

    model = MLP(
        in_dim=X_train_scaled.shape[1],
        hidden=hidden_dim,
        out_dim=num_classes
    ).to(device)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=5e-4)

    best_val_acc = 0.0
    best_model_weights = None
    epochs_no_improve = 0

    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0

        for batch_x, batch_y in train_loader:
            batch_x = batch_x.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()
            logits = model(batch_x)
            loss = criterion(logits, batch_y)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        avg_train_loss = epoch_loss / len(train_loader)

        val_preds = predict_in_batches(model, X_inner_val)
        val_acc = (val_preds == y_inner_val).float().mean().item()

        print(
            f"Epoch {epoch+1:3d}/{epochs} | "
            f"Train Loss: {avg_train_loss:.4f} | "
            f"Val Acc: {val_acc:.4f}"
        )

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_model_weights = copy.deepcopy(model.state_dict())
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1

        if epochs_no_improve >= patience:
            print(f"\nMLP early stopping triggered after {patience} epochs without improvement.")
            break

    print(f"\nLoading best MLP weights with validation accuracy: {best_val_acc:.4f}")
    model.load_state_dict(best_model_weights)

    mlp_test_preds = predict_in_batches(model, X_test_scaled)
    mlp_test_acc = accuracy_score(y_test.numpy(), mlp_test_preds.numpy())
    mlp_test_f1 = f1_score(y_test.numpy(), mlp_test_preds.numpy(), average='weighted')

    print(f"\n--- {fusion_name}: 30-70 MLP Test Results ---")
    print(f"MLP Test Accuracy:    {mlp_test_acc:.4f}")
    print(f"MLP Weighted Test F1: {mlp_test_f1:.4f}")

    print("\n--- MLP Classification Report ---")
    print(classification_report(y_test.numpy(), mlp_test_preds.numpy(), digits=4))

    late_fusion_30_70_results.append({
        "Split": "30-70",
        "Fusion": fusion_name,
        "Classifier": "MLP",
        "Accuracy": mlp_test_acc,
        "Weighted F1": mlp_test_f1
    })

    print("\n--- Training Logistic Regression on 30% train nodes ---")

    X_train_np = X_train_scaled.numpy()
    y_train_np = y_train.numpy()

    X_test_np = X_test_scaled.numpy()
    y_test_np = y_test.numpy()

    clf = LogisticRegression(max_iter=1000, multi_class='multinomial', n_jobs=-1)
    clf.fit(X_train_np, y_train_np)

    print("Evaluating Logistic Regression on 70% test nodes...")
    logreg_pred = clf.predict(X_test_np)

    logreg_acc = accuracy_score(y_test_np, logreg_pred)
    logreg_f1 = f1_score(y_test_np, logreg_pred, average='weighted')

    print(f"\n--- {fusion_name}: 30-70 Logistic Regression Test Results ---")
    print(f"Logistic Regression Test Accuracy:    {logreg_acc:.4f}")
    print(f"Logistic Regression Weighted Test F1: {logreg_f1:.4f}")

    print("\n--- Logistic Regression Classification Report ---")
    print(classification_report(y_test_np, logreg_pred, digits=4))

    late_fusion_30_70_results.append({
        "Split": "30-70",
        "Fusion": fusion_name,
        "Classifier": "Multinomial Logistic Regression",
        "Accuracy": logreg_acc,
        "Weighted F1": logreg_f1
    })

    del X_train, X_test, X_train_scaled, X_test_scaled
    del X_inner_train, X_inner_val, y_inner_train, y_inner_val
    torch.cuda.empty_cache()

    return pd.DataFrame(late_fusion_30_70_results)

### 30-70 Evaluation: Simple Concatenation

In [ ]:

# Simple concat :

S_struct = torch.load(r"/kaggle/input/datasets/mehulgoyal1729/s-products-normed-k100/S_products_normed_k100",map_location="cpu").float()

S_semantic = node_features.detach().cpu().float()

S_simple_concat_30_70 = torch.cat((S_struct, S_semantic), dim=1)

print(f"Simple concatenated embedding shape: {S_simple_concat_30_70.shape}")

results_30_70 = evaluate_late_fusion_30_70(
    S_eval=S_simple_concat_30_70,
    labels_eval=labels_tensor,
    train_idx_eval=train_idx_30_70,
    test_idx_eval=test_idx_30_70,
    fusion_name="Simple Concatenation",
    hidden_dim=512,
    batch_size=4096,
    epochs=200,
    patience=10
)

display(results_30_70)

del S_struct, S_semantic, S_simple_concat_30_70
torch.cuda.empty_cache()

Simple concatenated embedding shape: torch.Size([2449029, 200])

================================================================================
30-70 Split Evaluation: Simple Concatenation
================================================================================
Train nodes: 734732 | Test nodes: 1714297
Embedding dimension: 200

--- Training MLP on 30% train nodes ---
Epoch   1/200 | Train Loss: 1.0214 | Val Acc: 0.8206
Epoch   2/200 | Train Loss: 0.7304 | Val Acc: 0.8276
Epoch   3/200 | Train Loss: 0.6943 | Val Acc: 0.8326
Epoch   4/200 | Train Loss: 0.6759 | Val Acc: 0.8374
Epoch   5/200 | Train Loss: 0.6641 | Val Acc: 0.8388
Epoch   6/200 | Train Loss: 0.6564 | Val Acc: 0.8403
Epoch   7/200 | Train Loss: 0.6498 | Val Acc: 0.8412
Epoch   8/200 | Train Loss: 0.6465 | Val Acc: 0.8427
Epoch   9/200 | Train Loss: 0.6424 | Val Acc: 0.8428
Epoch  10/200 | Train Loss: 0.6398 | Val Acc: 0.8431
Epoch  11/200 | Train Loss: 0.6379 | Val Acc: 0.8451
Epoch  12/200 | Train Loss: 0.6361 | Val Acc: 0.8437
Epoch  13/200 | Train Loss: 0.6335 | Val Acc: 0.8443
Epoch  14/200 | Train Loss: 0.6324 | Val Acc: 0.8452
Epoch  15/200 | Train Loss: 0.6308 | Val Acc: 0.8456
Epoch  16/200 | Train Loss: 0.6300 | Val Acc: 0.8452
Epoch  17/200 | Train Loss: 0.6282 | Val Acc: 0.8458
Epoch  18/200 | Train Loss: 0.6280 | Val Acc: 0.8465
Epoch  19/200 | Train Loss: 0.6259 | Val Acc: 0.8464
Epoch  20/200 | Train Loss: 0.6259 | Val Acc: 0.8460
Epoch  21/200 | Train Loss: 0.6246 | Val Acc: 0.8469
Epoch  22/200 | Train Loss: 0.6250 | Val Acc: 0.8471
Epoch  23/200 | Train Loss: 0.6239 | Val Acc: 0.8472
Epoch  24/200 | Train Loss: 0.6248 | Val Acc: 0.8475
Epoch  25/200 | Train Loss: 0.6227 | Val Acc: 0.8473
Epoch  26/200 | Train Loss: 0.6227 | Val Acc: 0.8477
Epoch  27/200 | Train Loss: 0.6225 | Val Acc: 0.8467
Epoch  28/200 | Train Loss: 0.6216 | Val Acc: 0.8472
Epoch  29/200 | Train Loss: 0.6205 | Val Acc: 0.8476
Epoch  30/200 | Train Loss: 0.6204 | Val Acc: 0.8470
Epoch  31/200 | Train Loss: 0.6195 | Val Acc: 0.8473
Epoch  32/200 | Train Loss: 0.6204 | Val Acc: 0.8478
Epoch  33/200 | Train Loss: 0.6190 | Val Acc: 0.8469
Epoch  34/200 | Train Loss: 0.6198 | Val Acc: 0.8483
Epoch  35/200 | Train Loss: 0.6184 | Val Acc: 0.8469
Epoch  36/200 | Train Loss: 0.6184 | Val Acc: 0.8474
Epoch  37/200 | Train Loss: 0.6183 | Val Acc: 0.8479
Epoch  38/200 | Train Loss: 0.6181 | Val Acc: 0.8475
Epoch  39/200 | Train Loss: 0.6175 | Val Acc: 0.8480
Epoch  40/200 | Train Loss: 0.6168 | Val Acc: 0.8482
Epoch  41/200 | Train Loss: 0.6183 | Val Acc: 0.8483
Epoch  42/200 | Train Loss: 0.6168 | Val Acc: 0.8485
Epoch  43/200 | Train Loss: 0.6179 | Val Acc: 0.8478
Epoch  44/200 | Train Loss: 0.6175 | Val Acc: 0.8486
Epoch  45/200 | Train Loss: 0.6160 | Val Acc: 0.8479
Epoch  46/200 | Train Loss: 0.6169 | Val Acc: 0.8486
Epoch  47/200 | Train Loss: 0.6164 | Val Acc: 0.8488
Epoch  48/200 | Train Loss: 0.6167 | Val Acc: 0.8480
Epoch  49/200 | Train Loss: 0.6165 | Val Acc: 0.8486
Epoch  50/200 | Train Loss: 0.6155 | Val Acc: 0.8483
Epoch  51/200 | Train Loss: 0.6173 | Val Acc: 0.8480
Epoch  52/200 | Train Loss: 0.6159 | Val Acc: 0.8484
Epoch  53/200 | Train Loss: 0.6166 | Val Acc: 0.8482
Epoch  54/200 | Train Loss: 0.6162 | Val Acc: 0.8484
Epoch  55/200 | Train Loss: 0.6148 | Val Acc: 0.8492
Epoch  56/200 | Train Loss: 0.6159 | Val Acc: 0.8490
Epoch  57/200 | Train Loss: 0.6148 | Val Acc: 0.8486
Epoch  58/200 | Train Loss: 0.6148 | Val Acc: 0.8475
Epoch  59/200 | Train Loss: 0.6161 | Val Acc: 0.8487
Epoch  60/200 | Train Loss: 0.6149 | Val Acc: 0.8487
Epoch  61/200 | Train Loss: 0.6152 | Val Acc: 0.8470
Epoch  62/200 | Train Loss: 0.6149 | Val Acc: 0.8487
Epoch  63/200 | Train Loss: 0.6143 | Val Acc: 0.8486
Epoch  64/200 | Train Loss: 0.6148 | Val Acc: 0.8486
Epoch  65/200 | Train Loss: 0.6141 | Val Acc: 0.8487

MLP early stopping triggered after 10 epochs without improvement.

Loading best MLP weights with validation accuracy: 0.8492

--- Simple Concatenation: 30-70 MLP Test Results ---
MLP Test Accuracy:    0.8498
MLP Weighted Test F1: 0.8409

--- MLP Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.7933    0.8127    0.8029     80005
           1     0.7680    0.8284    0.7971     76882
           2     0.8960    0.9032    0.8996     81230
           3     0.7796    0.8107    0.7949    105742
           4     0.9250    0.9655    0.9448    468264
           5     0.8021    0.8664    0.8330     28500
           6     0.7988    0.8951    0.8442    111139
           7     0.9375    0.9360    0.9368    120539
           8     0.8997    0.9378    0.9183     77557
           9     0.9108    0.9036    0.9072     47150
          10     0.7594    0.8325    0.7943     36641
          11     0.6468    0.3589    0.4617     23055
          12     0.8331    0.8226    0.8278     92320
          13     0.8735    0.8180    0.8448     71078
          14     0.8562    0.3179    0.4636      2155
          15     0.8694    0.9255    0.8966     18837
          16     0.7226    0.7556    0.7387     58515
          17     0.9004    0.9404    0.9200     29635
          18     0.7708    0.6642    0.7135     34313
          19     0.5867    0.3451    0.4346     12206
          20     0.8204    0.8798    0.8490     15802
          21     0.6501    0.6371    0.6436     56556
          22     0.9384    0.5203    0.6695       615
          23     0.7763    0.2104    0.3311      2557
          24     0.4488    0.0972    0.1597     31784
          25     0.7482    0.3355    0.4633      2116
          26     0.0000    0.0000    0.0000       387
          27     0.0000    0.0000    0.0000       181
          28     0.0000    0.0000    0.0000      1378
          29     0.9790    0.8984    0.9370      1092
          30     0.0000    0.0000    0.0000       193
          31     0.0000    0.0000    0.0000       292
          32     0.0000    0.0000    0.0000       359
          33     0.0000    0.0000    0.0000        20
          34     0.0000    0.0000    0.0000       107
          35     0.6364    0.4667    0.5385        30
          36     0.0000    0.0000    0.0000       441
          37     0.0000    0.0000    0.0000       359
          38     0.0000    0.0000    0.0000        63
          39     0.0000    0.0000    0.0000        25
          40     0.0000    0.0000    0.0000         4
          41     0.0000    0.0000    0.0000        42
          42     0.8256    0.8040    0.8147     22750
          43     0.9842    0.3810    0.5493       979
          44     0.9964    0.6970    0.8202       396
          45     0.0000    0.0000    0.0000         6

    accuracy                         0.8498   1714297
   macro avg     0.5464    0.4689    0.4902   1714297
weighted avg     0.8401    0.8498    0.8409   1714297


--- Training Logistic Regression on 30% train nodes ---

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Evaluating Logistic Regression on 70% test nodes...

--- Simple Concatenation: 30-70 Logistic Regression Test Results ---
Logistic Regression Test Accuracy:    0.7910
Logistic Regression Weighted Test F1: 0.7772

--- Logistic Regression Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.6938    0.7670    0.7285     80005
           1     0.7427    0.7966    0.7687     76882
           2     0.8426    0.8827    0.8622     81230
           3     0.7328    0.7865    0.7587    105742
           4     0.8197    0.9001    0.8580    468264
           5     0.7960    0.8397    0.8173     28500
           6     0.7725    0.8776    0.8217    111139
           7     0.9160    0.9288    0.9224    120539
           8     0.8588    0.9154    0.8862     77557
           9     0.8909    0.8896    0.8903     47150
          10     0.7660    0.7974    0.7814     36641
          11     0.4861    0.1443    0.2225     23055
          12     0.7563    0.7113    0.7331     92320
          13     0.7997    0.7418    0.7697     71078
          14     0.5015    0.1568    0.2390      2155
          15     0.8477    0.9005    0.8733     18837
          16     0.6969    0.5362    0.6061     58515
          17     0.8989    0.9303    0.9144     29635
          18     0.7141    0.5264    0.6061     34313
          19     0.5009    0.2690    0.3501     12206
          20     0.8173    0.8408    0.8289     15802
          21     0.5731    0.5063    0.5377     56556
          22     0.6354    0.3967    0.4885       615
          23     0.5522    0.1201    0.1972      2557
          24     0.1575    0.0257    0.0442     31784
          25     0.4757    0.1900    0.2715      2116
          26     0.0000    0.0000    0.0000       387
          27     0.3151    0.1271    0.1811       181
          28     0.0588    0.0007    0.0014      1378
          29     0.6770    0.6795    0.6782      1092
          30     0.2571    0.0933    0.1369       193
          31     0.0000    0.0000    0.0000       292
          32     0.0833    0.0028    0.0054       359
          33     0.2500    0.1000    0.1429        20
          34     0.0000    0.0000    0.0000       107
          35     0.7619    0.5333    0.6275        30
          36     0.0000    0.0000    0.0000       441
          37     0.0526    0.0028    0.0053       359
          38     0.0000    0.0000    0.0000        63
          39     0.0000    0.0000    0.0000        25
          40     0.0000    0.0000    0.0000         4
          41     0.1250    0.0238    0.0400        42
          42     0.8157    0.7491    0.7810     22750
          43     0.7239    0.4392    0.5467       979
          44     0.8669    0.7071    0.7789       396
          45     0.0000    0.0000    0.0000         6

    accuracy                         0.7910   1714297
   macro avg     0.5051    0.4312    0.4501   1714297
weighted avg     0.7728    0.7910    0.7772   1714297

,Split,Fusion,Classifier,Accuracy,Weighted F1
0,30-70,Simple Concatenation,MLP,0.849829,0.840869
1,30-70,Simple Concatenation,Multinomial Logistic Regression,0.791039,0.777233

### 30-70 Evaluation: CLIP-based Contrastive Alignment

In [ ]:

# CLIP-based Contrastive Alignment fused embeddings

try:
    S_clip_30_70 = clip_fused.detach().cpu().float()
    print("Using existing variable: clip_fused")
except NameError:
    try:
        S_clip_30_70 = Z_fused.detach().cpu().float()
        print("Using existing variable: Z_fused")
    except NameError:
        S_clip_30_70 = torch.load(
            r"/kaggle/input/datasets/mehulgoyal1729/ogbn-products-clip-fused/Clip_Products.pth",
            map_location="cpu"
        ).float()
        print("Loaded CLIP-fused embeddings from saved Kaggle input path.")

print(f"CLIP-fused embedding shape: {S_clip_30_70.shape}")

results_30_70 = evaluate_late_fusion_30_70(
    S_eval=S_clip_30_70,
    labels_eval=labels_tensor,
    train_idx_eval=train_idx_30_70,
    test_idx_eval=test_idx_30_70,
    fusion_name="CLIP-based Contrastive Alignment",
    hidden_dim=512,
    batch_size=4096,
    epochs=200,
    patience=10
)

display(results_30_70)

del S_clip_30_70
torch.cuda.empty_cache()

Using existing variable: clip_fused
CLIP-fused embedding shape: torch.Size([2449029, 128])

================================================================================
30-70 Split Evaluation: CLIP-based Contrastive Alignment
================================================================================
Train nodes: 734732 | Test nodes: 1714297
Embedding dimension: 128

--- Training MLP on 30% train nodes ---
Epoch   1/200 | Train Loss: 0.8065 | Val Acc: 0.8591
Epoch   2/200 | Train Loss: 0.5701 | Val Acc: 0.8637
Epoch   3/200 | Train Loss: 0.5447 | Val Acc: 0.8660
Epoch   4/200 | Train Loss: 0.5337 | Val Acc: 0.8672
Epoch   5/200 | Train Loss: 0.5267 | Val Acc: 0.8681
Epoch   6/200 | Train Loss: 0.5221 | Val Acc: 0.8691
Epoch   7/200 | Train Loss: 0.5188 | Val Acc: 0.8693
Epoch   8/200 | Train Loss: 0.5159 | Val Acc: 0.8701
Epoch   9/200 | Train Loss: 0.5137 | Val Acc: 0.8703
Epoch  10/200 | Train Loss: 0.5110 | Val Acc: 0.8710
Epoch  11/200 | Train Loss: 0.5112 | Val Acc: 0.8709
Epoch  12/200 | Train Loss: 0.5089 | Val Acc: 0.8707
Epoch  13/200 | Train Loss: 0.5073 | Val Acc: 0.8707
Epoch  14/200 | Train Loss: 0.5063 | Val Acc: 0.8714
Epoch  15/200 | Train Loss: 0.5050 | Val Acc: 0.8714
Epoch  16/200 | Train Loss: 0.5046 | Val Acc: 0.8717
Epoch  17/200 | Train Loss: 0.5036 | Val Acc: 0.8716
Epoch  18/200 | Train Loss: 0.5034 | Val Acc: 0.8722
Epoch  19/200 | Train Loss: 0.5026 | Val Acc: 0.8714
Epoch  20/200 | Train Loss: 0.5011 | Val Acc: 0.8721
Epoch  21/200 | Train Loss: 0.5009 | Val Acc: 0.8723
Epoch  22/200 | Train Loss: 0.4996 | Val Acc: 0.8726
Epoch  23/200 | Train Loss: 0.4995 | Val Acc: 0.8721
Epoch  24/200 | Train Loss: 0.4990 | Val Acc: 0.8714
Epoch  25/200 | Train Loss: 0.4989 | Val Acc: 0.8716
Epoch  26/200 | Train Loss: 0.4985 | Val Acc: 0.8728
Epoch  27/200 | Train Loss: 0.4982 | Val Acc: 0.8727
Epoch  28/200 | Train Loss: 0.4983 | Val Acc: 0.8728
Epoch  29/200 | Train Loss: 0.4979 | Val Acc: 0.8725
Epoch  30/200 | Train Loss: 0.4976 | Val Acc: 0.8719
Epoch  31/200 | Train Loss: 0.4976 | Val Acc: 0.8722
Epoch  32/200 | Train Loss: 0.4965 | Val Acc: 0.8726
Epoch  33/200 | Train Loss: 0.4964 | Val Acc: 0.8714
Epoch  34/200 | Train Loss: 0.4966 | Val Acc: 0.8729
Epoch  35/200 | Train Loss: 0.4959 | Val Acc: 0.8720
Epoch  36/200 | Train Loss: 0.4958 | Val Acc: 0.8726
Epoch  37/200 | Train Loss: 0.4957 | Val Acc: 0.8728
Epoch  38/200 | Train Loss: 0.4951 | Val Acc: 0.8731
Epoch  39/200 | Train Loss: 0.4949 | Val Acc: 0.8734
Epoch  40/200 | Train Loss: 0.4959 | Val Acc: 0.8727
Epoch  41/200 | Train Loss: 0.4950 | Val Acc: 0.8730
Epoch  42/200 | Train Loss: 0.4948 | Val Acc: 0.8731
Epoch  43/200 | Train Loss: 0.4951 | Val Acc: 0.8724
Epoch  44/200 | Train Loss: 0.4948 | Val Acc: 0.8730
Epoch  45/200 | Train Loss: 0.4950 | Val Acc: 0.8722
Epoch  46/200 | Train Loss: 0.4944 | Val Acc: 0.8728
Epoch  47/200 | Train Loss: 0.4947 | Val Acc: 0.8729
Epoch  48/200 | Train Loss: 0.4945 | Val Acc: 0.8729
Epoch  49/200 | Train Loss: 0.4951 | Val Acc: 0.8730

MLP early stopping triggered after 10 epochs without improvement.

Loading best MLP weights with validation accuracy: 0.8734

--- CLIP-based Contrastive Alignment: 30-70 MLP Test Results ---
MLP Test Accuracy:    0.8722
MLP Weighted Test F1: 0.8654

--- MLP Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.8057    0.8405    0.8227     80005
           1     0.8040    0.8229    0.8133     76882
           2     0.9010    0.9284    0.9145     81230
           3     0.8022    0.8269    0.8144    105742
           4     0.9518    0.9768    0.9641    468264
           5     0.8487    0.8604    0.8545     28500
           6     0.8287    0.8978    0.8618    111139
           7     0.9462    0.9512    0.9487    120539
           8     0.9307    0.9380    0.9344     77557
           9     0.9235    0.9169    0.9201     47150
          10     0.7934    0.8394    0.8158     36641
          11     0.6037    0.5093    0.5525     23055
          12     0.8390    0.8800    0.8590     92320
          13     0.8890    0.8326    0.8599     71078
          14     0.8037    0.4863    0.6060      2155
          15     0.8758    0.9379    0.9058     18837
          16     0.7941    0.8328    0.8130     58515
          17     0.9144    0.9481    0.9309     29635
          18     0.7810    0.7353    0.7575     34313
          19     0.5971    0.4205    0.4935     12206
          20     0.8552    0.8741    0.8646     15802
          21     0.7089    0.6949    0.7018     56556
          22     0.9206    0.6407    0.7555       615
          23     0.6635    0.2761    0.3899      2557
          24     0.5946    0.1484    0.2375     31784
          25     0.6589    0.4802    0.5555      2116
          26     0.0000    0.0000    0.0000       387
          27     0.0000    0.0000    0.0000       181
          28     0.0000    0.0000    0.0000      1378
          29     0.9862    0.9167    0.9502      1092
          30     0.0000    0.0000    0.0000       193
          31     0.0000    0.0000    0.0000       292
          32     0.0000    0.0000    0.0000       359
          33     0.0000    0.0000    0.0000        20
          34     0.0000    0.0000    0.0000       107
          35     0.0000    0.0000    0.0000        30
          36     0.0000    0.0000    0.0000       441
          37     0.0000    0.0000    0.0000       359
          38     0.0000    0.0000    0.0000        63
          39     0.0000    0.0000    0.0000        25
          40     0.0000    0.0000    0.0000         4
          41     0.0000    0.0000    0.0000        42
          42     0.8275    0.8481    0.8376     22750
          43     0.9602    0.3453    0.5079       979
          44     1.0000    0.4318    0.6032       396
          45     0.0000    0.0000    0.0000         6

    accuracy                         0.8722   1714297
   macro avg     0.5393    0.4791    0.4967   1714297
weighted avg     0.8651    0.8722    0.8654   1714297


--- Training Logistic Regression on 30% train nodes ---

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

Evaluating Logistic Regression on 70% test nodes...

--- CLIP-based Contrastive Alignment: 30-70 Logistic Regression Test Results ---
Logistic Regression Test Accuracy:    0.8552
Logistic Regression Weighted Test F1: 0.8489

--- Logistic Regression Classification Report ---

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

              precision    recall  f1-score   support

           0     0.7866    0.8210    0.8034     80005
           1     0.7891    0.8010    0.7950     76882
           2     0.8967    0.9185    0.9074     81230
           3     0.7612    0.8084    0.7841    105742
           4     0.9404    0.9704    0.9552    468264
           5     0.8252    0.8487    0.8368     28500
           6     0.8181    0.8756    0.8459    111139
           7     0.9433    0.9444    0.9439    120539
           8     0.9187    0.9363    0.9274     77557
           9     0.9130    0.9137    0.9134     47150
          10     0.7857    0.8125    0.7989     36641
          11     0.5901    0.4414    0.5050     23055
          12     0.8278    0.8400    0.8338     92320
          13     0.8733    0.8223    0.8470     71078
          14     0.7703    0.4979    0.6048      2155
          15     0.8824    0.9144    0.8981     18837
          16     0.7706    0.7763    0.7734     58515
          17     0.9101    0.9338    0.9218     29635
          18     0.7510    0.6892    0.7188     34313
          19     0.5544    0.3805    0.4513     12206
          20     0.8366    0.8603    0.8483     15802
          21     0.6583    0.6546    0.6565     56556
          22     0.8901    0.6846    0.7739       615
          23     0.6008    0.2448    0.3479      2557
          24     0.3483    0.1428    0.2025     31784
          25     0.6739    0.4532    0.5420      2116
          26     0.8750    0.0181    0.0354       387
          27     0.5104    0.2707    0.3538       181
          28     0.2500    0.0007    0.0014      1378
          29     0.9795    0.9167    0.9470      1092
          30     0.6364    0.0363    0.0686       193
          31     0.0000    0.0000    0.0000       292
          32     0.2727    0.0084    0.0162       359
          33     0.0000    0.0000    0.0000        20
          34     0.0000    0.0000    0.0000       107
          35     0.6818    0.5000    0.5769        30
          36     0.0000    0.0000    0.0000       441
          37     0.0000    0.0000    0.0000       359
          38     0.0000    0.0000    0.0000        63
          39     0.0000    0.0000    0.0000        25
          40     0.0000    0.0000    0.0000         4
          41     0.0000    0.0000    0.0000        42
          42     0.8266    0.8212    0.8239     22750
          43     0.8963    0.4505    0.5996       979
          44     0.9841    0.6263    0.7654       396
          45     0.0000    0.0000    0.0000         6

    accuracy                         0.8552   1714297
   macro avg     0.5919    0.4921    0.5136   1714297
weighted avg     0.8462    0.8552    0.8489   1714297

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

,Split,Fusion,Classifier,Accuracy,Weighted F1
0,30-70,Simple Concatenation,MLP,0.849829,0.840869
1,30-70,Simple Concatenation,Multinomial Logistic Regression,0.791039,0.777233
2,30-70,CLIP-based Contrastive Alignment,MLP,0.872219,0.865385
3,30-70,CLIP-based Contrastive Alignment,Multinomial Logistic Regression,0.855186,0.848883